# This is a basic workflow to help you get started with Actions

name: Check formatting with Prettier

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prettier Check
        uses: creyD/prettier_action@v3.0
        with:
          dry: true
          prettier_options: --write **/*.{css,html,js,md}
